services:

  mongodb:
    networks:
      - maintenance-network
    image: 'mongo:latest'
    environment:
      - MONGO_INITDB_DATABASE=devDatabase
    secrets:
      - maintenance_secrets
    ports:
      - '27017:27017'

  rabbitmq:
    networks:
      - maintenance-network
    image: 'rabbitmq:latest'
    secrets:
      - maintenance_secrets
    ports:
      - '5672:5672'

  prometheus:
    networks:
      - maintenance-network
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped
    ports:
      - "3001:9090"
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
      - prom_data:/prometheus

  grafana:
    networks:
      - maintenance-network
    image: grafana/grafana:9.5.2
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    secrets:
      - maintenance_secrets
    volumes:
      - ./monitoring/provisioning/datasources:/etc/grafana/provisioning/datasources

  maintenance-service:
    networks:
      - maintenance-network
    image: maintenance-service
    container_name: maintenance-service
    ports:
      - "8080:8080"
    secrets:
      - maintenance_secrets

volumes:
  prom_data:

networks:
  maintenance-network:

secrets:
  maintenance_secrets:
    file: ./dev_secrets.txt
