logging:
  level:
    root: WARN
    org.springframework: INFO
    org.springframework.security: TRACE
    io.micrometer: INFO

server:
  port: 8080

management:
  server:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true

data:
  mongodb:
    uri: spring.data.mongodb.uri="mongodb://root:root@localhost:27017/devDatabase"
    writeConcern: 'W1'

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}