global:
  scrape_interval: 3s

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/actuator/prometheus'
    scheme: http
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'Maintenance manager service'